[package]
edition = "2018"

name = "project-cleanup"
version = "0.5.0"

description = "CLI tool to clean up and remove old generated code in your Rust, Javascript and Java projects"
repository = "https://github.com/woubuc/project-cleanup"
authors = ["Wouter Buckens <wouter@epicteddy.com> (https://www.woubuc.be)"]

readme = "README.md"
license = "MIT"

keywords = ["cleanup", "project", "clean", "delete", "free"]
categories = ["command-line-utilities"]

[dependencies]
colored = "1.8.0"
humansize = "1.1.0"
regex = "1.1.6"
